### ISSUE TITLE
Nullable Prop with complex object fails when value is null

### ISSUE THREAD

**Issue by gjovanov** [fastify/fluent-json-schema#45]
Hi there,
I'm not sure if this is a bug or a feature, but we have a property of a complext JSON type that can be null. And in the case that prop is null, the serializer throws an error:

```
TypeError: Cannot read property 'toJSON' of null
    at $mainroom (eval at build (C:\Dev\gjovanov\roomler\node_modules\fast-json-stringify\index.js:132:20), <anonymous>:184:30)
    at Object.$main (eval at build (C:\Dev\gjovanov\roomler\node_modules\fast-json-stringify\index.js:132:20), <anonymous>:119:17)
    at serialize (C:\Dev\gjovanov\roomler\node_modules\fastify\lib\validation.js:130:41)
    at preserializeHookEnd (C:\Dev\gjovanov\roomler\node_modules\fastify\lib\reply.js:263:15)
    at preserializeHook (C:\Dev\gjovanov\roomler\node_modules\fastify\lib\reply.js:250:5)
```

This is the model:

```javascript
const room = S.object()
  .prop('_id', S.string())
  .prop('owner', S.string())
  .prop('name', S.string())
  .prop('moderators', S.array().items(S.string()))
  .prop('members', S.array().items(S.string()))

const invite = S.object()
  .prop('_id', S.string())
  .prop('inviter', S.string())
  .prop('room', room) // THROWS an error if property room has null value
  .prop('email', S.string())
  .prop('type', S.string())
  .prop('status', S.string().enum(statuses))
  .prop('createdAt', S.string())
  .prop('updatedAt', S.string())
```

Do you have any suggestion to support nullable props with complex JSON objects?
Thanks.

/GJ

**Comment by mcollina** [comment]
This is likely a bug of fast-json-stringify.

Il giorno mar 27 ago 2019 alle 11:06 Goran Jovanov <notifications@github.com>
ha scritto:

**Comment by Eomm** [comment]
@gjovanov could you try this setup?

```
const invite = S.object()
  .prop('_id', S.string())
  .prop('inviter', S.string())
  .prop('room', S.mixed([room, S.TYPES.NULL]))
  .prop('email', S.string())
  .prop('type', S.string())
  .prop('status', S.string().enum(statuses))
  .prop('createdAt', S.string())
  .prop('updatedAt', S.string())
```

**Comment by gjovanov** [comment]
Thanks for the suggestion @Eomm . I just tried it, but it didn't work. This is the error being thrown:

```
Error: Invalid 'types'. It must be an array of types. Valid types are string | number | boolean | integer | object | array | null
    at Object.mixed (C:\Dev\gjovanov\roomler\node_modules\fluent-schema\src\FluentSchema.js:148:13)
    at Object.mixed (C:\Dev\gjovanov\roomler\node_modules\fluent-schema\src\FluentSchema.js:171:23)
```

Only this is allowed:
`.prop('room', S.mixed([S.TYPES.OBJECT, S.TYPES.NULL]))`

But it has some side-effects like missing room props later.

**Comment by aboutlo** [comment]
I think the `room` property should be marked as required. 

```js
it.only('throws an execption if the property is null', () => {
      const room = S.object()
        .prop('_id', S.string())
        .prop('owner', S.string())
        .prop('name', S.string())
        .prop('moderators', S.array().items(S.string()))
        .prop('members', S.array().items(S.string()))

      const invite = S.object()
        .prop('inviter', S.string())
        .prop('room', room) // THROWS an error if property room has null value
        .prop('email', S.string())
        .prop('type', S.string())
        .prop('createdAt', S.string())
        .prop('updatedAt', S.string())
        .required(['room'])

      const ajv = new Ajv().valueOf()
      const validate = ajv.compile(invite.valueOf())
      const isValid = validate({
        room: null,
      })

      console.log(validate.errors)
      expect(isValid).toBeFalsy()
    })
```

**Comment by gjovanov** [comment]
It made sense your proposal since null value means no value set by the user, whereat undefined means initialized but no value has been assigned yet. Hence I was eager to try out your suggestion, however I'm still getting the same error:

```
TypeError: Cannot read property 'toJSON' of null
    at $mainroom (eval at build (C:\Dev\gjovanov\roomler\node_modules\fast-json-stringify\index.js:134:20), <anonymous>:195:30)
    at Object.$main (eval at build (C:\Dev\gjovanov\roomler\node_modules\fast-json-stringify\index.js:134:20), <anonymous>:119:17)
    at serialize (C:\Dev\gjovanov\roomler\node_modules\fastify\lib\validation.js:131:41)
```

Not sure how come your tests are passing. It seems to be related to fast-json-stringify.

**Comment by mcollina** [comment]
As I've said in https://github.com/fastify/fluent-schema/issues/45#issuecomment-525214037, this is likely a bug in fast-json-stringify and not this library.
